T1
kpiotrowski/IO2_Project pull request #2
Opened 2017-04-02 17:49 UTC by Terenter

2017-04-02 18:03 UTC, kpiotrowski requested changes

2017-04-02 18:03 UTC, kpiotrowski commented on IO2P/resourceAdder.cs
> +        private String strDBPass = "sfd9879IjgkDslkhgdgl98sdfG9sdUFSD98sdf9wfdgHG78vgsf809few0";
Radzę trzymać ustawienia lokalnie w ENV'ach np. Jest to również konieczne jak travis będzie sobie odpalał testy (tam będzie lokalna baza danych postawiona przez travisa i ustawienia do niej będą brane z envów. Pisałem dokładnie jak się nazwywają w tickecie). Teraz będę musiał zmienić hasło bo zna je już cały świat :(

2017-04-02 18:18 UTC, Terenter commented on IO2P/resourceAdder.cs
> +        private String strDBPass = "sfd9879IjgkDslkhgdgl98sdfG9sdUFSD98sdf9wfdgHG78vgsf809few0";
Mój błąd. Wybacz

2017-04-02 18:41 UTC, Terenter commented on IO2P/resourceAdder.cs
> +        private String strDBPass = "sfd9879IjgkDslkhgdgl98sdfG9sdUFSD98sdf9wfdgHG78vgsf809few0";
Adres hosta też?

2017-04-02 20:02 UTC, kpiotrowski commented on IO2P/resourceAdder.cs
> +        private String strDBPass = "sfd9879IjgkDslkhgdgl98sdfG9sdUFSD98sdf9wfdgHG78vgsf809few0";
Hosta też dajmy. Powiedzmy DB_HOST. W zasadzie port też można dać konfigurowalny jako DB_PORT. Travis będzie miał bazę lokalnie (127.0.0.1) więc na pewno musimy mieć to w konfigu.

2017-04-02 20:21 UTC, Terenter commented on IO2P/resourceAdder.cs
> +        private String strDBPass = "sfd9879IjgkDslkhgdgl98sdfG9sdUFSD98sdf9wfdgHG78vgsf809few0";
Teraz powinno być w porządku.

2017-04-03 21:39 UTC, kpiotrowski approved these changes

2017-04-04 11:45 UTC, merged